# How often (in ticks) to update the hidden block's location
# 20 ticks / second
update-interval: 10

# Blocks away a player should be before they no longer receive updates
update-distance: 170

# If set true logs player use
verbose-logging: false

# Whether to render the player invisible while the block is shown
make-players-invisible: true

# Whether to undisguise a player when they attack something
undisguise-on-pvp: true

# If true, notifies any OP or user with BlockDisguise.admin about updates
notify-about-updates: true

# Can be overriden with permission BlockDisguise.allowAllBlocks
allowed-blocks:
  - STONE
  - GRASS
  - DIRT
  - COBBLESTONE
  - WOOD
  - SAPLING
  - BEDROCK
  - WATER
  - STATIONARY_WATER
  - LAVA
  - STATIONARY_LAVA
  - SAND
  - GRAVEL
  - GOLD_ORE
  - IRON_ORE
  - COAL_ORE
  - LOG
  - LEAVES
  - SPONGE
  - GLASS
  - LAPIS_ORE
  - LAPIS_BLOCK
  - DISPENSER
  - SANDSTONE
  - NOTE_BLOCK
  - BED_BLOCK
  - POWERED_RAIL
  - DETECTOR_RAIL
  - PISTON_STICKY_BASE
  - WEB
  - LONG_GRASS
  - DEAD_BUSH
  - PISTON_BASE
  - WOOL
  - YELLOW_FLOWER
  - RED_ROSE
  - BROWN_MUSHROOM
  - RED_MUSHROOM
  - GOLD_BLOCK
  - IRON_BLOCK
  - DOUBLE_STEP
  - STEP
  - BRICK
  - TNT
  - BOOKSHELF
  - MOSSY_COBBLESTONE
  - OBSIDIAN
  - TORCH
  - FIRE
  - MOB_SPAWNER
  - WOOD_STAIRS
  - CHEST
  - REDSTONE_WIRE
  - DIAMOND_ORE
  - DIAMOND_BLOCK
  - WORKBENCH
  - CROPS
  - SOIL
  - FURNACE
  - BURNING_FURNACE
  - SIGN_POST
  - WOODEN_DOOR
  - LADDER
  - RAILS
  - COBBLESTONE_STAIRS
  - WALL_SIGN
  - LEVER
  - STONE_PLATE
  - IRON_DOOR_BLOCK
  - WOOD_PLATE
  - REDSTONE_ORE
  - REDSTONE_TORCH_OFF
  - REDSTONE_TORCH_ON
  - GLOWING_REDSTONE_ORE
  - STONE_BUTTON
  - SNOW
  - ICE
  - SNOW_BLOCK
  - CACTUS
  - CLAY
  - SUGAR_CANE_BLOCK
  - JUKEBOX
  - FENCE
  - PUMPKIN
  - NETHERRACK
  - SOUL_SAND
  - GLOWSTONE
  - PORTAL
  - JACK_O_LANTERN
  - CAKE_BLOCK
  - DIODE_BLOCK_OFF
  - DIODE_BLOCK_ON
  - LOCKED_CHEST
  - TRAP_DOOR
  - MONSTER_EGGS
  - SMOOTH_BRICK
  - HUGE_MUSHROOM_1
  - HUGE_MUSHROOM_2
  - IRON_FENCE
  - THIN_GLASS
  - MELON_BLOCK
  - PUMPKIN_STEM
  - MELON_STEM
  - VINE
  - FENCE_GATE
  - BRICK_STAIRS
  - SMOOTH_STAIRS
  - MYCEL
  - WATER_LILY
  - NETHER_BRICK
  - NETHER_FENCE
  - NETHER_BRICK_STAIRS
  - NETHER_WARTS
  - ENCHANTMENT_TABLE
  - BREWING_STAND
  - CAULDRON
  - ENDER_PORTAL
  - ENDER_PORTAL_FRAME
  - ENDER_STONE
  - DRAGON_EGG
  - REDSTONE_LAMP_OFF
  - REDSTONE_LAMP_ON
  - WOOD_DOUBLE_STEP
  - WOOD_STEP
  - COCOA
  - SANDSTONE_STAIRS
  - EMERALD_ORE
  - ENDER_CHEST
  - EMERALD_BLOCK
  - SPRUCE_WOOD_STAIRS
  - BIRCH_WOOD_STAIRS
  - JUNGLE_WOOD_STAIRS
  - COMMAND
  - BEACON
  - COBBLE_WALL
  - FLOWER_POT
  - CARROT
  - POTATO
  - WOOD_BUTTON
  - SKULL
  - ANVIL
  - TRAPPED_CHEST
  - GOLD_PLATE
  - IRON_PLATE
  - REDSTONE_COMPARATOR_OFF
  - REDSTONE_COMPARATOR_ON
  - DAYLIGHT_DETECTOR
  - REDSTONE_BLOCK
  - QUARTZ_ORE
  - HOPPER
  - QUARTZ_BLOCK
  - QUARTZ_STAIRS
  - ACTIVATOR_RAIL
  - DROPPER